---
tower_templates:
  - name: SERVER / RHEL7 - Register
    project: Automated Management
    playbook: server_register.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    limit: rhel7
    extra_vars:
      org_id: "Default_Organization"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: PREFIX
          required: false
        - question_name: Choose Environment
          type: multiplechoice
          variable: env
          choices:
            - Dev
            - QA
            - Prod
          required: true

  - name: SERVER / CentOS7 - Register
    project: Automated Management
    playbook: server_register.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    limit: centos7
    extra_vars:
      org_id: "Default_Organization"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: PREFIX
          required: false
        - question_name: Choose Environment
          type: multiplechoice
          variable: env
          choices:
            - Dev
            - QA
            - Prod
          required: true

  - name: SATELLITE / RHEL - Publish Content View
    project: Automated Management
    playbook: satellite_publish.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    extra_vars:
      env: Dev
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true

  - name: SATELLITE / CentOS - Publish Content View
    project: Automated Management
    playbook: satellite_publish.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    extra_vars:
      env: Dev
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true

  - name: SATELLITE / RHEL - Promote Content View
    project: Automated Management
    playbook: satellite_promote.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Current Lifecycle Environment
          variable: current_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Next Lifecycle Environment
          variable: lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true

  - name: SATELLITE / CentOS - Promote Content View
    project: Automated Management
    playbook: satellite_promote.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Content View
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Current Lifecycle Environment
          variable: current_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Next Lifecycle Environment
          variable: lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true  

  - name: SATELLITE / Delete host(s) in "node_group"
    project: Automated Management
    playbook: satellite_delete_host.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    extra_vars:
      node_group: env_CentOS7_Dev

  - name: SATELLITE / Transfer converted host(s) to another LE
    project: Automated Management
    playbook: satellite_transfer_host.yml
    inventory: ALL Development
    credentials:
      - Satellite Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select CentOS Lifecycle Environment to transfer nodes from
          variable: centos_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Select target RHEL Lifecycle Environment
          variable: rhel_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true

  - name: SERVER / RHEL7 - Patch
    project: Automated Management
    playbook: server_patch.yml
    inventory: Workshop Inventory
    use_fact_cache: true
    credentials:
      - Workshop Credential
    limit: rhel7
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Environment
          type: multiplechoice
          variable: server_type
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Check
          type: multiplechoice
          variable: check_only
          choices:
            - 'yes'
            - 'no'
          required: true

  - name: SERVER / CentOS7 - Patch
    project: Automated Management
    playbook: server_patch.yml
    inventory: Workshop Inventory
    use_fact_cache: true
    credentials:
      - Workshop Credential
    limit: centos7
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select Environment
          type: multiplechoice
          variable: server_type
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Check
          type: multiplechoice
          variable: check_only
          choices:
            - 'yes'
            - 'no'
          required: true

  - name: SERVER / RHEL7 - Fact Scan
    project: Fact Scan
    playbook: scan_facts.yml
    inventory: Workshop Inventory
    ask_limit_on_launch: true
    use_fact_cache: true
    credentials:
      - Workshop Credential
    limit: rhel7

  - name: SERVER / CentOS7 - Fact Scan
    project: Fact Scan
    playbook: scan_facts.yml
    inventory: Workshop Inventory
    ask_limit_on_launch: true
    use_fact_cache: true
    credentials:
      - Workshop Credential
    limit: centos7

  - name: SERVER / Start node via ec2_node_tools
    description: Start node - selection via EC2 instance tags
    project: Automated Management
    playbook: node_startup.yml
    inventory: Workshop Inventory
    limit: control
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM
          short_name: node*

  - name: SERVER / Stop node via ec2_node_tools
    description: Stop node - selection via EC2 instance tags
    project: Automated Management
    playbook: node_shutdown.yml
    inventory: Workshop Inventory
    limit: control
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM
          short_name: node*

  - name: CONVERT2RHEL / 01 - Take node snapshot
    description: Take node snapshot - selection via EC2 instance tags
    project: Automated Management
    playbook: snapshot_instance.yml
    inventory: Workshop Inventory
    limit: control
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          short_name: node*
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM
          username: centos

  - name: CONVERT2RHEL / 02 - Upgrade OS to latest release
    description: Upgrade OS to latest available packages
    project: Automated Management
    playbook: upgrade_instance.yml
    inventory: CentOS7 Development
    credentials:
      - Workshop Credential
    extra_vars:
      ec2_region: us-east-1

  - name: CONVERT2RHEL / 03 - convert2rhel
    description: Convert OS to RHEL OS via targetted LE
    project: Automated Management
    playbook: c2r.yml
    inventory: ALL Development
    credentials:
      - Workshop Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select CentOS Group to convert
          variable: centos_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^CentOS.*$') | map(attribute='name') | list}}"
          required: true
        - question_name: Select target RHEL Group to convert to
          variable: rhel_lifecycle_environment
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['lifecycle_environments'] | selectattr('name', 'match', '^RHEL.*$') | map(attribute='name') | list}}"
          required: true

  - name: CONVERT2RHEL / 98 - Revert node state via snapshot
    description: Revert via snapshot - selection via EC2 instance tags
    project: Automated Management
    playbook: snapshot_revert.yml
    inventory: Workshop Inventory
    limit: control
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM
          username: centos

  - name: CONVERT2RHEL / 99 - Delete snapshot
    description: Delete snapshot - selection via EC2 snapshot tags
    project: Automated Management
    playbook: snapshot_delete.yml
    inventory: Workshop Inventory
    limit: control
    extra_vars:
      ec2_region: us-east-1
      snapshots:
        tags:
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM

  - name: EC2 / Set instance tags based on Satellite(Foreman) facts
    description: Set instance tags - selection via existing EC2 instance tags
    project: Automated Management
    playbook: query_satellite_resource_info_hosts_set_instance_tags.yml
    inventory: Workshop Inventory
    credentials:
      - Satellite Credential
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          guid: EC2_NAME_PREFIX
          Student: STUDENT_NAME_WITH_NUM
          short_name: node*

  - name: EC2 / Get instance details via ec2_node_tools role
    description: Utilize ec2_node_tools role to display info available per instance/node
    project: Automated Management
    playbook: node_details_via_ec2_node_tools.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          guid: EC2_NAME_PREFIX
          Student: student1
          short_name: node*

  - name: EC2 / Update Route53
    description: Update Route53 records with external IPs
    project: Automated Management
    playbook: refresh_route53_dns.yml
    inventory: Workshop Inventory
    credentials:
      - Workshop Credential
    extra_vars:
      ec2_region: us-east-1
      instances:
        tags:
          Workshop: EC2_NAME_PREFIX
      student: student1
      workshop_dns_zone: rhtelco.io

  - name: TOWER / Update CentOS7 Dev inventories
    project: Automated Management
    playbook: tower_inventory_source_update_centos7_dev.yml
    inventory: Workshop Inventory
    credentials:
      - Tower Credential

  - name: TOWER / Update inventories via dynamic sources
    project: Automated Management
    playbook: tower_inventory_source_update.yml
    inventory: Workshop Inventory
    credentials:
      - Tower Credential
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Select inventory to update
          variable: content_view
          type: multiplechoice
          choices: "{{ hostvars['satellite.example.com']['foreman_content_views'] | selectattr('name', 'defined') | map(attribute='name') | list}}"
          required: true
        - question_name: Choose Environment
          type: multiplechoice
          variable: env
          choices:
            - Dev
            - QA
            - Prod
          required: true
